# Generated by Django 5.2.5 on 2025-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('shop_admin', 'Shop Admin'), ('staff', 'Staff')], default='shop_admin', max_length=20),
        ),
    ]
