# Generated by Django 5.2.5 on 2025-11-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
        ('shop', '0013_alter_shop_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='The shop this staff member belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_users', to='shop.shop'),
        ),
    ]
