# Generated by Django 5.2.5 on 2025-11-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop',
        ),
    ]
