# Generated by Django 5.2.5 on 2025-11-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_shop'),
        ('shop', '0014_alter_shop_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='shop.shop'),
        ),
    ]
