# Generated by Django 5.2.5 on 2025-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_code_shop_established_date_alter_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
