# Generated by Django 5.2.5 on 2025-09-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='roll_number',
        ),
    ]
