# Generated by Django 5.2.5 on 2025-09-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shop_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.AddField(
            model_name='shop',
            name='address_line_1',
            field=models.CharField(default='Temporary Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='address_line_2',
            field=models.CharField(default='Temporary Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Temporary Address', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Temporary Address', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(default='Temporary Address', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(default='Temporary Address', max_length=50),
            preserve_default=False,
        ),
    ]
