# Generated by Django 5.2.5 on 2025-11-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Pending'), ('confirmed', '🔵 Confirmed'), ('shipped', '🚚 Shipped'), ('delivered', '✅ Delivered'), ('cancelled', '❌ Cancelled'), ('paid', '💰 Paid')], default='pending', max_length=20),
        ),
    ]
