# Generated by Django 5.2.5 on 2025-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shop_address_shop_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='map_location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
