# Generated by Django 5.2.5 on 2025-11-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
