# Generated by Django 5.2.5 on 2025-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_map_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
