# Generated by Django 5.2.5 on 2025-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
