# Generated by Django 5.2.5 on 2025-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_price_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
