# Generated by Django 5.2.5 on 2025-11-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item_barcode_price_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='admin_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
